name: Heart Stroke CI/CD

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Pull the repository
      - name: Checkout the repository
        uses: actions/checkout@v4

      # Step 2: (Optional) Setup Docker buildx
      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@v2

      # Step 3: Login into DockerHub
      - name: Login into Docker
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Step 4: Build and push Docker image
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/heart-stroke:latest

      # Step 5: Deploy it in EC2 instance
      - name: Deploy on EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            if ! command -v docker &> /dev/null
            then
              echo "Docker not found, installing..."
              sudo yum update -y
              sudo yum install -y docker
              sudo systemctl start docker
              sudo systemctl enable docker
            fi

            sudo docker --version

            sudo docker pull ${{ secrets.DOCKER_USERNAME }}/heart-stroke:latest
            sudo docker stop heart-stroke || true
            sudo docker rm heart-stroke || true
            sudo docker run -d -p 80:8000 --name heart-stroke ${{ secrets.DOCKER_USERNAME }}/heart-stroke:latest